- 단축키 ESC / Enter : 명령 모드/수정모드
- Run : ctrl/shift/alt + enter
- 셀 지우기 : x 
- 코드 : Y, 마크다운 : m
- 


###### 파이썬 특징
 - 빌드 없이 바로 실행 가능(인터프린터, 스크립트)
 - 

In [ ]:
연산자
- + * / //는 몫만 **는 제곱 
논리연산자 and or not

주석 ''' ''', """ """ -> 번거롭기 때문에 보통 홀따옴표를 사용함

In [2]:
1+3, 1*3, 1-3, 1/3, 3//3, 3**3, True or False, not True

(4, 3, -2, 0.3333333333333333, 1, 27, True, False)

In [3]:
#조건문 
if 5 > 3: #if (5 > 3): 가능하나 보통 괄호 없이 사용함
    print('5>3')

5>3


In [4]:
#반복문 지정된 횟수만큼 반복
for i in range(3): 
    print(i)

0
1
2


In [6]:
#while 조건을 만족할때까지 반복
import random
#0~1 랜덤값을 생성하는데 0.1보다 작은 값을 얻겠다.
while(True):
    v = random.random()
    print(v)
    if v < 0.1:
        break

0.8957306789661201
0.23971435344165004
0.5337393119003538
0.6691203549161074
0.07405075692085061


In [15]:
#함수
'''
기존
int add(int a, int b){
    return a+b:
}
'''
def add(a,b):
    return a+b
add(1,3), add(1.5,3.3), add('abc','1'), add(1, 1)

(4, 4.8, 'abc1', 2)

In [23]:
#생성자
class Lotto:
    def __init__(self, k):
        #nums = [] #전역변수 self.nums = []
        self.nums = []
        for i in range(k):
            self.nums.append(random.randint(1,45))
        print(self.nums)

In [26]:
lotto1 = Lotto(3)
lotto2 = Lotto(5)
lotto1.nums

[21, 19, 39]
[33, 6, 14, 33, 8]


[21, 19, 39]

#데이터 타입 
 - 딕셔너리 {} : {키:값, 키:값} 엑셀의 컬럼 이름: 키, 컬럼의 값들:값
 - 리스트 [] : [값, 값, 값] 수정가능 언제든지 편리하게 데이터를 저장
 - 튜플() : (값, 값, 값) 수정불가 함수에서 값들을 여러개 리턴할때

In [29]:
d = {'age':30, 'city':'Seoul'}
l = [10, 'a', 'city', [1,2,3]]
t = (10, 'a', 'city', [1,2,3])
d, l,t 

({'age': 30, 'city': 'Seoul'},
 [10, 'a', 'city', [1, 2, 3]],
 (10, 'a', 'city', [1, 2, 3]))

In [39]:
l[0],l[-1], l[1:3],l[1:], l[0:], l[:] #인덱스는 반드시 정수여야 함
#[시작위치:끝위치전]

(10,
 [1, 2, 3],
 ['a', 'city'],
 ['a', 'city', [1, 2, 3]],
 [10, 'a', 'city', [1, 2, 3]],
 [10, 'a', 'city', [1, 2, 3]])

In [40]:
[1,2,3]+[4,5,6] #List, dic,set 연산용으로 사용이 불가능, 메모리 사용량이 크고 느림

[1, 2, 3, 4, 5, 6]

In [47]:
import numpy as np
numpy.arange(1,10), numpy.arange(1,10,2)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [49]:
np.array([1,2,3]) + numpy.array([4,5,6])

array([5, 7, 9])

#야후 s&p 500주식 데이터를 읽습니다.
#csv 또는 pandas로 읽을 수 있습니다.

In [52]:
import pandas

In [55]:
stock = pandas.read_csv('snp500.csv')

In [56]:
stock.shape #(20,7) 로우 20, 컬럼 7

(20, 7)

In [57]:
stock

Date         Open         High          Low        Close  \
0   2019-05-20  2841.939941  2853.860107  2831.290039  2840.229980   
1   2019-05-21  2854.020020  2868.879883  2854.020020  2864.360107   
2   2019-05-22  2856.060059  2865.469971  2851.110107  2856.270020   
3   2019-05-23  2836.699951  2836.699951  2805.489990  2822.239990   
4   2019-05-24  2832.409912  2841.360107  2820.189941  2826.060059   
5   2019-05-28  2830.030029  2840.510010  2801.580078  2802.389893   
6   2019-05-29  2790.250000  2792.030029  2766.060059  2783.020020   
7   2019-05-30  2786.939941  2799.000000  2776.739990  2788.860107   
8   2019-05-31  2766.149902  2768.979980  2750.520020  2752.060059   
9   2019-06-03  2751.530029  2763.070068  2728.810059  2744.449951   
10  2019-06-04  2762.639893  2804.489990  2762.639893  2803.270020   
11  2019-06-05  2818.090088  2827.280029  2800.919922  2826.149902   
12  2019-06-06  2828.510010  2852.100098  2822.449951  2843.489990   
13  2019-06-07  2852.870117  2884.969971  2852.870117  2873.340088   
14  2019-06-10  2885.830078  2904.770020  2885.510010  2886.729980   
15  2019-06-11  2903.270020  2910.610107  2878.530029  2885.719971   
16  2019-06-12  2882.729980  2888.570068  2874.679932  2879.840088   
17  2019-06-13  2886.239990  2895.239990  2881.989990  2891.639893   
18  2019-06-14  2886.820068  2894.449951  2879.620117  2886.979980   
19  2019-06-17  2889.750000  2897.270020  2887.300049  2889.669922   

      Adj Close      Volume  
0   2840.229980  3288870000  
1   2864.360107  3218700000  
2   2856.270020  3192510000  
3   2822.239990  3891980000  
4   2826.060059  2887390000  
5   2802.389893  4121410000  
6   2783.020020  3700050000  
7   2788.860107  3273790000  
8   2752.060059  3981020000  
9   2744.449951  3943810000  
10  2803.270020  3810430000  
11  2826.149902  3548830000  
12  2843.489990  3396410000  
13  2873.340088  3220250000  
14  2886.729980  3209210000  
15  2885.719971  3548420000  
16  2879.840088  3034130000  
17  2891.639893  3069810000  
18  2886.979980  2922330000  
19  2889.669922  1579314342

In [60]:
arr = np.array(stock)
arr.shape

(20, 7)

In [76]:
arr

array([['2019-05-20', 2841.939941, 2853.860107, 2831.290039, 2840.22998,
        2840.22998, 3288870000],
       ['2019-05-21', 2854.02002, 2868.8798829999996, 2854.02002,
        2864.360107, 2864.360107, 3218700000],
       ['2019-05-22', 2856.060059, 2865.469971, 2851.110107, 2856.27002,
        2856.27002, 3192510000],
       ['2019-05-23', 2836.699951, 2836.699951, 2805.48999, 2822.23999,
        2822.23999, 3891980000],
       ['2019-05-24', 2832.409912, 2841.360107, 2820.189941, 2826.060059,
        2826.060059, 2887390000],
       ['2019-05-28', 2830.030029, 2840.51001, 2801.580078, 2802.389893,
        2802.389893, 4121410000],
       ['2019-05-29', 2790.25, 2792.030029, 2766.060059, 2783.02002,
        2783.02002, 3700050000],
       ['2019-05-30', 2786.939941, 2799.0, 2776.73999, 2788.860107,
        2788.860107, 3273790000],
       ['2019-05-31', 2766.149902, 2768.97998, 2750.52002, 2752.060059,
        2752.060059, 3981020000],
       ['2019-06-03', 2751.530029, 2763.07006

In [95]:
o=arr[:,1]
o.shape

(20,)

In [96]:
#최대값, 최소값, 평균b

max(o), min(o), np.max(o), np.min(o), np.std(o), np.median(o), np.mean(o)

(2903.27002,
 2751.530029,
 2903.27002,
 2751.530029,
 45.016996538592394,
 2839.319946,
 2837.1390014000003)

In [80]:
arr[:,4]#arr[:,-3]

array([2840.22998, 2864.360107, 2856.27002, 2822.23999, 2826.060059,
       2802.389893, 2783.02002, 2788.860107, 2752.060059, 2744.449951,
       2803.27002, 2826.149902, 2843.48999, 2873.340088, 2886.72998,
       2885.719971, 2879.840088, 2891.639893, 2886.97998, 2889.669922],
      dtype=object)

In [81]:
arr[:,-3]

array([2840.22998, 2864.360107, 2856.27002, 2822.23999, 2826.060059,
       2802.389893, 2783.02002, 2788.860107, 2752.060059, 2744.449951,
       2803.27002, 2826.149902, 2843.48999, 2873.340088, 2886.72998,
       2885.719971, 2879.840088, 2891.639893, 2886.97998, 2889.669922],
      dtype=object)

In [82]:
arr[:,1:-2]#arr[:,1:5]

array([[2841.939941, 2853.860107, 2831.290039, 2840.22998],
       [2854.02002, 2868.8798829999996, 2854.02002, 2864.360107],
       [2856.060059, 2865.469971, 2851.110107, 2856.27002],
       [2836.699951, 2836.699951, 2805.48999, 2822.23999],
       [2832.409912, 2841.360107, 2820.189941, 2826.060059],
       [2830.030029, 2840.51001, 2801.580078, 2802.389893],
       [2790.25, 2792.030029, 2766.060059, 2783.02002],
       [2786.939941, 2799.0, 2776.73999, 2788.860107],
       [2766.149902, 2768.97998, 2750.52002, 2752.060059],
       [2751.530029, 2763.070068, 2728.810059, 2744.449951],
       [2762.639893, 2804.48999, 2762.639893, 2803.27002],
       [2818.090088, 2827.280029, 2800.919922, 2826.149902],
       [2828.51001, 2852.100098, 2822.449951, 2843.48999],
       [2852.8701170000004, 2884.969971, 2852.8701170000004, 2873.340088],
       [2885.830078, 2904.77002, 2885.51001, 2886.72998],
       [2903.27002, 2910.610107, 2878.530029, 2885.719971],
       [2882.72998, 2888.570068

In [93]:
v4 = arr[:,1:5]
v4.shape

(20, 4)

In [106]:
#axis : 축  0 : 열별 또는 1 행별
np.max(v4, axis=0),np.argmax(v4,axis=0)

(array([2903.27002, 2910.610107, 2887.300049, 2891.639893], dtype=object),
 array([15, 15, 19, 17], dtype=int64))

In [105]:
np.argmax(v4,axis=0)

array([15, 15, 19, 17], dtype=int64)

In [107]:
np.min(v4, axis=0),np.argmin(v4, axis=0)

(array([2751.530029, 2763.070068, 2728.810059, 2744.449951], dtype=object),
 array([9, 9, 9, 9], dtype=int64))

In [127]:
#주가가 가장많이 상승한 날짜를 찾아보세요 (정답 : 몇번째 행)
#종가 - 시작가
date1=arr[:,0]
open1= arr[:,1]
close1=arr[:,4]
a=np.array(close1)-np.array(open1)
x = np.argmax(a)
date1[x]

'2019-06-04'

In [136]:
data1=arr[:,0:]
data1[np.argmax(np.array(data1[:,4])-np.array(data1[:,1])),0]

'2019-06-04'

가격 상승하는날 거래량이 많아질까?
전날 가격이 상승하면 다음날 시작가격은 더 높은 가격에서 시작할까?
가격변동이 크면 거래량도 많아질까?

--------------------------------------
어제/오늘 현황 분석이 끝났는데 내일은 어떻게 될까?
방법 : 1. 통계(R), 2. 머신런닝

In [140]:
vol = data1[:,-1]


In [143]:
#조건부 검색
a= np.array([1,2,3,4])
even = a%2==0
even #boolean 마스크
a[even]

array([2, 4])

In [159]:
#가격 상승하는날 거래량이 많아질까? 답 아님
vol = data1[:,-1]
gap=np.array(data1[:,4])-np.array(data1[:,1])
vol[gap>0], vol[gap<0], np.mean(vol[gap>0]), np.mean(vol[gap<0]), np.mean(vol[gap>0]) > np.mean(vol[gap<0])

(array([3218700000, 3192510000, 3273790000, 3810430000, 3548830000,
        3396410000, 3220250000, 3209210000, 3069810000, 2922330000],
       dtype=object),
 array([3288870000, 3891980000, 2887390000, 4121410000, 3700050000,
        3981020000, 3943810000, 3548420000, 3034130000, 1579314342],
       dtype=object),
 3286227000.0,
 3397639434.2,
 False)

In [171]:
np.zeros(shape=(2,3,4,5), dtype=np.int32)

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [177]:
np.ones(shape=(2,3,4,5), dtype=np.int32)

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

In [180]:
np.ones(shape=(4,3,2), dtype=np.int32)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [181]:
np.ones(shape=(2,4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [183]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [187]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [192]:
np.linspace(1,10,4) #n1(1)부터 n2(10)까지 똑같은 크기로 n3(4)등분해라

array([ 1.,  4.,  7., 10.])

In [196]:
np.random.rand(2,3)

array([[0.42415415, 0.29063683, 0.922214  ],
       [0.92871101, 0.47648053, 0.15107132]])

In [199]:
np.random.normal(size=(2,3)) #정규분포

array([[ 0.22322217,  0.3712361 , -0.1351476 ],
       [ 1.03539138,  0.41049248,  1.40975643]])

In [201]:
np.random.randint(low=1, high=10,size=(3,3))

array([[8, 3, 2],
       [5, 5, 4],
       [2, 3, 5]])

In [202]:
np.random.uniform(low=1, high=10,size=(3,3)) #균등

array([[3.88090698, 2.16781406, 9.49540305],
       [9.35731015, 7.93377293, 7.88546836],
       [1.64610832, 1.26939268, 8.86777746]])

In [209]:
a = np.ones(shape=(3,2),dtype=np.int)
b = np.ones(shape=(3,2),dtype=np.float) 
a+b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [211]:
#행우선 저장
a = np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [213]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [225]:
b=a.reshape(3,2)

In [226]:
#차원, 모양, 총요소개수, 데이터타입 메모리사용량byte
b.ndim, b.shape, b.size, b.dtype, b.nbytes

(2, (3, 2), 6, dtype('int32'), 24)

In [227]:
b.flatten()

array([0, 1, 2, 3, 4, 5])

In [229]:
a=np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

- 1,4,7
- 6,7,8
- 1,2,4,5,7,8
- 4,5,7,8

In [240]:
a[:,1]#1,4,7
a[2,:]# 6,7,8
a[:,1:]# 1,2,4,5,7,8
a[1:,1:]# 4,5,7,8

array([[4, 5],
       [7, 8]])

In [243]:
a[:,1].flatten(),a[2,:].flatten(),a[:,1:].flatten(),a[1:,1:].flatten()

(array([1, 4, 7]),
 array([6, 7, 8]),
 array([1, 2, 4, 5, 7, 8]),
 array([4, 5, 7, 8]))

In [252]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [258]:
# 5,6,9,10
# 9,10,11
a[1:,1:-1].flatten(), a[-1,1:]

(array([ 5,  6,  9, 10]), array([ 9, 10, 11]))

In [280]:
c=np.arange(2*3*4).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [269]:
c[0,0,],c[1,0,],c[0,:,1],c[1,:,-1]

(array([0, 1, 2, 3]),
 array([12, 13, 14, 15]),
 array([1, 5, 9]),
 array([15, 19, 23]))

In [278]:
#[6,10], [17,18,19], [13,14,17,18]
c[0,1:,2], c[1,1,1:], c[1,0:-1,1:-1].flatten()

(array([ 6, 10]), array([17, 18, 19]), array([13, 14, 17, 18]))

In [285]:
c.shape
c.reshape((6,4)), np.reshape(c,(4,6))

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]), array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]))

In [288]:
c.reshape((2,-1)) #-1 알아서 맞춰서 바꿔라

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [290]:
#concatenate
a=np.arange(6).reshape(2,3)
b=np.arange(6,12).reshape(2,3)
a,b

(array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [294]:
c=np.concatenate((a,b,a), axis=0)
c, c.shape

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [ 0,  1,  2],
        [ 3,  4,  5]]), (6, 3))

In [295]:
d=np.concatenate((a,b,a), axis=1)
d, d.shape

(array([[ 0,  1,  2,  6,  7,  8,  0,  1,  2],
        [ 3,  4,  5,  9, 10, 11,  3,  4,  5]]), (2, 9))

In [296]:
#stack
a.shape, b.shape

((2, 3), (2, 3))

In [299]:
c=np.stack((a,b,a),axis=0)
c, c.shape

(array([[[ 0,  1,  2],
         [ 3,  4,  5]],
 
        [[ 6,  7,  8],
         [ 9, 10, 11]],
 
        [[ 0,  1,  2],
         [ 3,  4,  5]]]), (3, 2, 3))

In [300]:
d=np.stack((a,b,a),axis=1)
d, d.shape

(array([[[ 0,  1,  2],
         [ 6,  7,  8],
         [ 0,  1,  2]],
 
        [[ 3,  4,  5],
         [ 9, 10, 11],
         [ 3,  4,  5]]]), (2, 3, 3))

In [304]:
e=np.stack((a,b,a,b),axis=2)
e, e.shape

(array([[[ 0,  6,  0,  6],
         [ 1,  7,  1,  7],
         [ 2,  8,  2,  8]],
 
        [[ 3,  9,  3,  9],
         [ 4, 10,  4, 10],
         [ 5, 11,  5, 11]]]), (2, 3, 4))

In [351]:
#stack 예
kor = [80, 90, 99]
eng = [70, 50, 60]
score=np.stack((kor,eng),axis=1)
score

array([[80, 70],
       [90, 50],
       [99, 60]])

In [352]:
math = np.array([20,30,40]).reshape(3,1)
math
score=np.concatenate((score,math),axis=1)
score

array([[80, 70, 20],
       [90, 50, 30],
       [99, 60, 40]])

In [353]:
score_4= np.array([100,90,90]).reshape(1,3)
score_4
score=np.concatenate((score,score_4),axis=0)
score

array([[ 80,  70,  20],
       [ 90,  50,  30],
       [ 99,  60,  40],
       [100,  90,  90]])

In [357]:
#사람별 평균
np.sum(score,axis=1),np.mean(score,axis=1),

(array([170, 170, 199, 280]),
 array([56.66666667, 56.66666667, 66.33333333, 93.33333333]))

In [358]:
#과목별 평균
np.sum(score,axis=0),np.mean(score,axis=0),

(array([369, 270, 180]), array([92.25, 67.5 , 45.  ]))

In [359]:
#시험을 가장 잘 본 학생의 평균 점수는
idx=np.argmax(np.sum(score,axis=1))
np.mean(score[idx,:])

93.33333333333333

In [361]:
#fmt='%.2f'소수2번째 %d 는 정수
np.savetxt('test.txt',score,fmt='%d',delimiter='|',encoding='UTF=8')

In [370]:
result=np.loadtxt('test.txt',dtype=np.int32, delimiter='|')
result

array([[ 80,  70,  20],
       [ 90,  50,  30],
       [ 99,  60,  40],
       [100,  90,  90]])

In [379]:
result[:,::-1] #시작부터 끝까지 거꾸로

array([[ 20,  70,  80],
       [ 30,  50,  90],
       [ 40,  60,  99],
       [ 90,  90, 100]])

In [380]:
result[:,::2] #시작부터 끝까지 스텝(간격) 2

array([[ 80,  20],
       [ 90,  30],
       [ 99,  40],
       [100,  90]])

In [383]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [385]:
#시작부터 끝까지 2칸씩 뛰면서
#첫번째 요소부터 끝까지 2칸씩 뛰면서
a[::2],a[1::2]

(array([0, 2, 4, 6, 8]), array([1, 3, 5, 7, 9]))

In [389]:
#2번째 요소부터 6번째 요소까지 2칸씩 뛰면서
#[시작:끝:간격]
a[2:7:2]

array([2, 4, 6])

In [393]:
np.split(a,[3,6]) # 3,6위치를 잘라라

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

In [392]:
np.split(a,[4,8]) # 4,8위치를 잘라라

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([8, 9])]

In [394]:
np.split(a,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [400]:
#브로드캐스팅
a = np.array([0,10,20,30])
a = np.stack((a,a,a),1)
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [401]:
b= np.array([0,1,2])
b

array([0, 1, 2])

In [406]:
a+b, a[0,:]+b

(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]), array([0, 1, 2]))

In [407]:
a = np.array([0,10,20,30]).reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [408]:
b= np.array([0,1,2])
b

array([0, 1, 2])

In [410]:
a*b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [411]:
3>9

False

In [412]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [420]:
mask=a > 5
mask

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [418]:
a[mask]


array([6, 7, 8, 9])

In [419]:
np.logical_not(mask)

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [421]:
np.logical_and(mask,mask)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [423]:
#짝수이면서 2보다 큰값을 뽑으세요
mask1=a%2==0
mask1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [424]:
mask2=a>2
mask2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [426]:
mask3=np.logical_and(mask1,mask2)

In [427]:
a[mask3]

array([4, 6, 8])

In [431]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#주식 데이터 2개를 받아서 concatenate로 붙이세요
#df =pandas.read_csv()
#arr0=np.array(df0[]) 필요한 숫자 부분만 
#arr1=np.array(df1[])
#arr = np.concatenate((arr0,arr1),axis=0)

In [437]:
#Date,Open,High,Low,Close,Adj Close,Volume
df1 = pandas.read_csv('dow_1year_ago.csv')
df2 = pandas.read_csv('dow_2year_ago.csv')
df1.shape, df2.shape

((251, 7), (251, 7))

In [446]:
arr = np.concatenate((df2,df1), axis=0)
arr.shape, arr

((502, 7), array([['2017-06-19', 21444.75, 21528.990234, ..., 21528.990234,
         21528.990234, 289400000],
        ['2017-06-20', 21521.25, 21535.029297, ..., 21467.140625,
         21467.140625, 310200000],
        ['2017-06-21', 21466.390625, 21492.619141, ..., 21410.029297,
         21410.029297, 292500000],
        ...,
        ['2019-06-13', 26036.939453, 26146.910156, ..., 26106.769531,
         26106.769531, 213400000],
        ['2019-06-14', 26076.359375, 26162.279297, ..., 26089.609375,
         26089.609375, 208020000],
        ['2019-06-17', 26108.5, 26165.779297, ..., 26112.529297,
         26112.529297, 199500000]], dtype=object))

In [447]:
arr1 = np.array(df1)
arr2 = np.array(df2)
arr = np.concatenate((arr1,arr2),axis=0)
arr.shape, arr

((502, 7), array([['2018-06-18', 24944.279297, 25003.099609, ..., 24987.470703,
         24987.470703, 337070000],
        ['2018-06-19', 24763.589844, 24763.589844, ..., 24700.210938,
         24700.210938, 376380000],
        ['2018-06-20', 24771.169922, 24804.759766, ..., 24657.800781,
         24657.800781, 359520000],
        ...,
        ['2018-06-13', 25328.650391, 25362.070313, ..., 25201.199219,
         25201.199219, 329700000],
        ['2018-06-14', 25254.650391, 25332.5, ..., 25175.310547,
         25175.310547, 341170000],
        ['2018-06-15', 25116.710938, 25130.820313, ..., 25090.480469,
         25090.480469, 659370000]], dtype=object))

In [456]:
arr[0]

array(['2018-06-18', 24944.279297, 25003.099609, 24825.769531,
       24987.470703, 24987.470703, 337070000], dtype=object)

In [470]:
#Date,Open,High,Low,Close,Adj Close,Volume
#각각의 평균값
np.mean(arr[:,1:],axis=0).astype(np.int32)

array([    24525,     24642,     24399,     24527,     24527, 332232888])

In [471]:
#가격변동(close-open)이 가장 큰 때가 언제인지 날짜를 알고 싶다.
close=arr[:,-2]
open=arr[:,1]
gap=np.abs(close-open)
idx=np.argmax(gap)
arr[idx,0], gap[idx], idx

('2018-02-08', 1041.8398430000016, 413)